BOX_RAM = "1024"
BOX_CPU = "1"
# BOX_BASE = "generic/centos8"
BOX_BASE = "centos/7"

MASTER_NODE_NAME = "agidgetS"
MASTER_NODE_IP = "192.168.56.110"

WORKER_NODE_NAME = "agidgetSW"
WORKER_NODE_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_BASE
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = BOX_RAM
    vb.cpus = BOX_CPU
    # enable internet access inside Vagrant
    # https://stackoverflow.com/questions/51060639/virtualbox-what-is-the-difference-of-natdnsproxy1-and-natdnshostresolver1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.provision "shell", inline: "yum install -y net-tools"

  # Server
  config.vm.define MASTER_NODE_NAME do |master|
    master.vm.hostname = MASTER_NODE_NAME
    master.vm.network "private_network", ip: "192.168.56.110"
    # https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name
    master.vm.provider "virtualbox" do |v|
      v.name = MASTER_NODE_NAME
    end
    master.vm.provision "file", source: "~/.ssh/id_rsa_iot.pub", destination: "/tmp/id_rsa_iot.pub"
    # https://github.com/flannel-io/flannel/blob/master/Documentation/troubleshooting.md#vagrant
    master.vm.provision "shell", inline: <<-MASTER
      mkdir -p /root/.ssh
      cat /tmp/id_rsa_iot.pub > /root/.ssh/authorized_keys
    MASTER
  end

  # Worker
  config.vm.define WORKER_NODE_NAME do |worker|
    worker.vm.hostname = WORKER_NODE_NAME
    worker.vm.network "private_network", ip: WORKER_NODE_IP
    # https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name
    worker.vm.provider "virtualbox" do |v|
      v.name = WORKER_NODE_NAME
    end
    worker.vm.provision "file", source: "~/.ssh/id_rsa_iot", destination: "/tmp/id_rsa_iot"
    worker.vm.provision "shell", inline: <<-WORKER
      mkdir -p /root/.ssh
      mv /tmp/id_rsa_iot /root/.ssh/id_rsa_iot
    WORKER
  end

end


# curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --flannel-iface=eth1" sh -